theme: jekyll-theme-leap-day

# Proteínas Blanco, Rutas terapéuticas en el tratamiento de COVID-19

## COVID-19, ¿Porqué es tan importante el tratamiento?

## El ciclo viral

## Proteínas virales

## Objetivos terapéuticos

### Spike

### Proteína 2

## ¿Porqué estas proteinas y no otras?

## Datos curiosos

### Un poco sobre nosotras
